src/main/java/uk/gov/laa/pfla/auth/service/controllers/ReportsController.java
src/main/java/uk/gov/laa/pfla/auth/service/dao/MappingTableDao.java
src/main/java/uk/gov/laa/pfla/auth/service/services/MappingTableService.java
src/test/java/uk/gov/laa/pfla/auth/service/controllers/ReportsControllerTest.java

Prevent multiple endpoint requests from accumulating multiple json response objects (clear arraylists each time)

LPF-200-Create-end-points-view

---

.github/workflows/deploy.yml
deployments/templates/deployment.yml
pom.xml
src/main/java/uk/gov/laa/pfla/auth/service/PflaApplication.java
src/main/java/uk/gov/laa/pfla/auth/service/controllers/ReportsController.java
src/main/java/uk/gov/laa/pfla/auth/service/dao/ReportViewsDao.java
src/main/java/uk/gov/laa/pfla/auth/service/models/MappingTableModel.java
src/main/java/uk/gov/laa/pfla/auth/service/services/MappingTableService.java
src/main/java/uk/gov/laa/pfla/auth/service/services/ReportService.java
src/test/java/uk/gov/laa/pfla/auth/service/builders/ReportListResponseTestBuilder.java
src/test/java/uk/gov/laa/pfla/auth/service/controllers/ReportsControllerTest.java
src/test/java/uk/gov/laa/pfla/auth/service/dao/ReportViewsDaoTest.java
src/test/java/uk/gov/laa/pfla/auth/service/service/ReportServiceTest.java

Code to create a CSV STREAM of MOJFIN db reports data.
I have left some code in and commented it out in case we need to go back to the CSV File implementation (using files in the Java code)

Lpf 208 java i o file operations to create csv file

---

README.md
src/main/java/uk/gov/laa/pfla/auth/service/controllers/ReportsController.java

Testbranch

---

.github/workflows/deploy.yml

Tidying up, and enabling UAT job

Lpf 222 set up cicd pipeline for uat env

---

README.md

[LPF-213]: Fix typo

---

deployments/development/deployment.tpl
deployments/development/ingress.tpl
deployments/development/service.tpl
src/main/resources/application-development.yml

This PR introduces new configuration for a brand new Development environment. Additionally includes changes to UAT environment

[LPF-510]: Update configuration to reflect UAT environment

---

src/test/java/uk/gov/laa/gpfd/service/MappingTableServiceTest.java

new version of previous branch due to signing issues

Added tests for mapping table service class

---

src/main/java/uk/gov/laa/gpfd/graph/AzureGraphClient.java
src/main/java/uk/gov/laa/gpfd/graph/StubbedGraphClient.java
src/main/resources/application-local.yml

With this we can, when on a local profile, access the Spring Actuator endpoint without logging in

LPF-465 - Actuator endpoint is open access

---

pom.xml
src/main/java/uk/gov/laa/gpfd/config/SecurityConfigLocal.java
src/main/resources/application-local.yml
src/test/java/uk/gov/laa/gpfd/config/builders/HttpSecuritySessionManagementConfigurerBuilderLocalTest.java

Local profile is set up to allow you to access pages without needing to login to Azure

LPF-193 - setup local running for acceptance tests - disable login when local

---

.github/workflows/deploy_to_uat.yml
deployments/uat/deployment.tpl
deployments/uat/ingress.tpl
deployments/uat/service-monitor.tpl
deployments/uat/service.tpl
src/main/resources/application-uat.yml

We can connect to the new domain using HTTPS:

[LPF-556] Using only ingress SSL certificate and removing application SSL

---

.github/workflows/deploy_to_prod.yml
deployments/prod/deployment.tpl
deployments/prod/ingress.tpl
deployments/prod/network-policy.tpl
deployments/prod/service-monitor.tpl
deployments/prod/service.tpl
src/main/resources/application-prod.yml
src/main/resources/application.yml

We are adding the production environment with deployment pipeline, infrastructure and production application. We could successfully get the reports:

[LPF 519]  Production environment

---

src/main/java/uk/gov/laa/gpfd/dao/MappingTableDao.java

[LPF-546]: Add production server to swagger - update sql

---

src/main/java/uk/gov/laa/gpfd/dao/ReportTrackingTableDao.java
src/main/resources/DDL_CreateGpfdTablesMojfin.sql

Feature/lpf 551 create UUID for primary keys

---

src/main/java/uk/gov/laa/gpfd/dao/MappingTableDao.java

Replaced wrong error message when report id not found

replaced incorrect error message with correct one

---

.github/workflows/deploy_to_dev.yml
deployments/development/prometheus-rules.tpl
deployments/prod/prometheus-rules.tpl
deployments/uat/prometheus-rules.tpl

We are having an issue with the secret manager rules so decide to remove it:

[LPF-602] Remove invalid prometheus rule

---

deployments/development/prometheus-rules.tpl
deployments/prod/prometheus-rules.tpl
deployments/uat/prometheus-rules.tpl

This should fix the alerts message not being generated properly:
We also have tweaked the nginx alerts to get triggered

Fix alert message

---

pom.xml

Fix https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-9396739

[LPF-719]: Path Equivalence - Security Issue

---

.github/workflows/deploy.yml
.github/workflows/deploy_to_env.yml

We had lost some metrics:
We have tested they are back:

[LPF-599] Bring back some Grafana metrics

---

.github/workflows/deploy.yml
deployments/templates/deployment.yml
deployments/templates/ingress.yml
src/main/resources/application-uat.yml

We also have updated the secrets in AWS Secret Manager and harmonise the variables across environments.

[LPF-599] Fix deployment pipeline for production

---

pom.xml
src/main/java/uk/gov/laa/gpfd/services/ReportService.java

Remove dependency to simplify dependency management

Remove dependency org.apache.commons:commons-csv from 1.13.0

---

.github/workflows/deploy.yml
.github/workflows/deploy_testable.yml
deployments/templates/ingress.yml

This PR updates the API URLs for all environments (DEV, UAT, PROD) to align with the Cloud Platform custom domain convention:
- Env prefix for non-production (e.g., dev.*, uat.*).
- No env prefix for production.
Changes
Updated API URLs:
DEV:
Old: https://dev.get-legal-aid-data-api.service.justice.gov.uk/
NEW: https://laa-get-payments-finance-data-api-dev.apps.live.cloud-platform.service.justice.gov.uk/
UAT:
Old: https://uat.get-legal-aid-data-api.service.justice.gov.uk/
NEW: https://laa-get-payments-finance-data-api-uat.apps.live.cloud-platform.service.justice.gov.uk/
PROD:
Old: https://get-legal-aid-data-api.service.justice.gov.uk/
NEW: https://laa-get-payments-finance-data-api-prod.apps.live.cloud-platform.service.justice.gov.uk/
```
> curl -vk …
```

[LPF-817]: Set the right URL for the UI

---

.github/workflows/deploy_acceptance_tests_to_env.yml
.github/workflows/deploy_api_to_env.yml

[LPF-776]: Remove Liquibase Dependency and Externalize Database Initialization - fix the template

---

.github/pull_request_template.md

JIRA: [LPF-923](https://dsdmoj.atlassian.net/browse/LPF-923)
We add a PR template to remind us of what a good PR looks like
[LPF-923]: https://dsdmoj.atlassian.net/browse/LPF-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Documentation: LPF-923 add a PR template

---

src/main/java/uk/gov/laa/gpfd/config/AppConfig.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application-uat.yml

JIRA: [LPF-1023](https://dsdmoj.atlassian.net/browse/LPF-1023)
- Before we can test that local changes to template running work, we need to get local working. Achieve this by using the properties driver rather than hardcoding it to Oracle. That way local can run S3.
- Code has been deployed to dev and tested.
[LPF-1023]: https://dsdmoj.atlassian.net/browse/LPF-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LPF-1023 - fix issue whereby local mode would not start
